import { missing, spec, type SportFeatureContract } from "./spec.ts";

/** MLB is the first deep specialization. Missing advanced stats stay missing. */
export const MLB_FEATURE_CONTRACT: SportFeatureContract = {
  sport: "mlb",
  displayName: "MLB",
  independentEngine: true,
  features: [
    spec({ key: "starting_pitcher_home", label: "starting pitcher", group: "pitching", availability: "partial", source: "ESPN probable + startersFetchedAt", usableAsFeature: true, notes: "Name/ERA/WHIP only when startersFetchedAt is proven." }),
    spec({ key: "starting_pitcher_away", label: "starting pitcher away", group: "pitching", availability: "partial", source: "ESPN probable + startersFetchedAt", usableAsFeature: true, notes: "Missing starter lowers dataQuality. Do not invent." }),
    missing("fip", "FIP", "pitching", "FanGraphs / Savant pitcher page with as-of date"),
    missing("xfip", "xFIP", "pitching", "FanGraphs / Savant point-in-time dump"),
    spec({ key: "era_home", label: "ERA", group: "pitching", availability: "partial", source: "ESPN probable season ERA", usableAsFeature: true, notes: "Live only with startersFetchedAt. Historical dump ERA is unproven." }),
    spec({ key: "era_away", label: "ERA away", group: "pitching", availability: "partial", source: "ESPN probable season ERA", usableAsFeature: true, notes: "Same provenance as home ERA." }),
    missing("k_pct", "K%", "pitching", "FanGraphs / Savant"),
    missing("bb_pct", "BB%", "pitching", "FanGraphs / Savant"),
    missing("k_bb_pct", "K-BB%", "pitching", "FanGraphs / Savant pitcher splits"),
    spec({ key: "whip_home", label: "WHIP", group: "pitching", availability: "partial", source: "ESPN probable WHIP", usableAsFeature: true, notes: "Live only with startersFetchedAt." }),
    spec({ key: "whip_away", label: "WHIP away", group: "pitching", availability: "partial", source: "ESPN probable WHIP", usableAsFeature: true, notes: "Live only with startersFetchedAt." }),
    missing("recent_pitcher_workload", "recent pitcher workload", "pitching", "Pitcher game log (pitches / IP last start) with known_at = game final"),
    missing("pitch_count_rest", "pitch count / rest", "pitching", "Pitcher game log"),
    missing("bullpen_era_fip", "bullpen ERA/FIP", "bullpen", "Team bullpen as-of from game logs"),
    missing("bullpen_usage_1d", "bullpen usage last 1 day", "bullpen", "Bullpen IP last 1 day from box scores"),
    missing("bullpen_usage_3d", "bullpen usage last 3 days", "bullpen", "Bullpen IP last 3 days from box scores"),
    missing("wrc_plus", "team wRC+", "offense", "FanGraphs team/player offense with as-of date"),
    missing("handedness_splits", "handedness splits", "offense", "FanGraphs / Savant platoon splits"),
    missing("confirmed_lineup", "confirmed lineup", "lineup", "MLB official lineup card with posted timestamp"),
    spec({ key: "key_hitter_absences", label: "key hitter absences", group: "lineup", availability: "partial", source: "ESPN injury board + player-impact", usableAsFeature: true, notes: "Injury impact only when injuriesFetchedAt is proven." }),
    missing("park_factor", "park factor", "context", "Static park-factor table keyed on venue. Name is available; numeric factor is not."),
    spec({ key: "venue", label: "park / venue name", group: "context", availability: "available", source: "ESPN scoreboard venue + fetchedAt", usableAsFeature: true, notes: "Name only. Do not invent a park factor from it." }),
    missing("temperature", "temperature", "weather", "Structured weather observation timestamp"),
    missing("wind", "wind", "weather", "Structured wind speed/direction"),
    missing("humidity", "humidity", "weather", "Weather API with observation timestamp"),
    spec({ key: "weather_string", label: "weather string", group: "weather", availability: "partial", source: "ESPN weather + weatherFetchedAt", usableAsFeature: true, notes: "Raw string. Do not parse invented numbers." }),
    spec({ key: "team_form_home", label: "team recent form", group: "form", availability: "available", source: "historical_games priors (finals only)", usableAsFeature: true, notes: "last5/last10/win% from completed priors." }),
    spec({ key: "home_away", label: "home/away", group: "context", availability: "available", source: "game card", usableAsFeature: true, notes: "Home indicator is known at schedule time." }),
    spec({ key: "rest_days", label: "rest", group: "context", availability: "partial", source: "prior finals start-to-start", usableAsFeature: true, notes: "RestDays is leak-safe from priors." }),
    missing("travel", "travel", "context", "Miles / timezone from a dated schedule feed"),
    spec({ key: "market_opener", label: "market opener", group: "market", availability: "partial", source: "proven openCapturedAt quote", usableAsFeature: true, usableAsStake: true, notes: "Unproven numeric openers are audit-only, not features or stakes." }),
    spec({ key: "market_current", label: "current market price", group: "market", availability: "available", source: "DK capturedAt quote", usableAsFeature: true, usableAsStake: true, notes: "Two-way only. Close is never current." }),
    spec({ key: "market_movement", label: "market movement", group: "market", availability: "partial", source: "proven open vs current implied", usableAsFeature: true, notes: "Only when both quotes are proven pregame. Close is not a move endpoint." }),
  ],
};
