/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DeskRouteRouteImport } from './routes/desk/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ResponsiblePlayRouteImport } from './routes/responsible-play'
import { Route as SlateRouteImport } from './routes/slate'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppPicksRouteImport } from './routes/app/picks'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskAdvancedRouteImport } from './routes/desk/advanced'
import { Route as DeskHealthRouteImport } from './routes/desk/health'
import { Route as DeskModelsRouteImport } from './routes/desk/models'
import { Route as DeskRecordRouteImport } from './routes/desk/record'
import { Route as DeskSlateRouteImport } from './routes/desk/slate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRouteRoute = DeskRouteRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsiblePlayRoute = ResponsiblePlayRouteImport.update({
  id: '/responsible-play',
  path: '/responsible-play',
  getParentRoute: () => rootRouteImport,
} as any)
const SlateRoute = SlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPicksRoute = AppPicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => AppRouteRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskAdvancedRoute = DeskAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskHealthRoute = DeskHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskModelsRoute = DeskModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskRecordRoute = DeskRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskSlateRoute = DeskSlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => DeskRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/desk': typeof DeskRouteRouteWithChildren
  '/advanced': typeof AdvancedRoute
  '/health': typeof HealthRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/slate': typeof SlateRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/history': typeof AppHistoryRoute
  '/app/picks': typeof AppPicksRoute
  '/desk/advanced': typeof DeskAdvancedRoute
  '/desk/health': typeof DeskHealthRoute
  '/desk/models': typeof DeskModelsRoute
  '/desk/record': typeof DeskRecordRoute
  '/desk/slate': typeof DeskSlateRoute
  '/app/': typeof AppIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/health': typeof HealthRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/slate': typeof SlateRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/history': typeof AppHistoryRoute
  '/app/picks': typeof AppPicksRoute
  '/desk/advanced': typeof DeskAdvancedRoute
  '/desk/health': typeof DeskHealthRoute
  '/desk/models': typeof DeskModelsRoute
  '/desk/record': typeof DeskRecordRoute
  '/desk/slate': typeof DeskSlateRoute
  '/app': typeof AppIndexRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/desk': typeof DeskRouteRouteWithChildren
  '/advanced': typeof AdvancedRoute
  '/health': typeof HealthRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/slate': typeof SlateRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/history': typeof AppHistoryRoute
  '/app/picks': typeof AppPicksRoute
  '/desk/advanced': typeof DeskAdvancedRoute
  '/desk/health': typeof DeskHealthRoute
  '/desk/models': typeof DeskModelsRoute
  '/desk/record': typeof DeskRecordRoute
  '/desk/slate': typeof DeskSlateRoute
  '/app/': typeof AppIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/desk'
    | '/advanced'
    | '/health'
    | '/ledger'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/responsible-play'
    | '/slate'
    | '/terms'
    | '/app/account'
    | '/app/history'
    | '/app/picks'
    | '/desk/advanced'
    | '/desk/health'
    | '/desk/models'
    | '/desk/record'
    | '/desk/slate'
    | '/app/'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/health'
    | '/ledger'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/responsible-play'
    | '/slate'
    | '/terms'
    | '/app/account'
    | '/app/history'
    | '/app/picks'
    | '/desk/advanced'
    | '/desk/health'
    | '/desk/models'
    | '/desk/record'
    | '/desk/slate'
    | '/app'
    | '/desk'
    | '/api/auth/$'
    | '/api/cron/tick'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/desk'
    | '/advanced'
    | '/health'
    | '/ledger'
    | '/login'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/responsible-play'
    | '/slate'
    | '/terms'
    | '/app/account'
    | '/app/history'
    | '/app/picks'
    | '/desk/advanced'
    | '/desk/health'
    | '/desk/models'
    | '/desk/record'
    | '/desk/slate'
    | '/app/'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DeskRouteRoute: typeof DeskRouteRouteWithChildren
  AdvancedRoute: typeof AdvancedRoute
  HealthRoute: typeof HealthRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordRoute: typeof RecordRoute
  ResponsiblePlayRoute: typeof ResponsiblePlayRoute
  SlateRoute: typeof SlateRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-play': {
      id: '/responsible-play'
      path: '/responsible-play'
      fullPath: '/responsible-play'
      preLoaderRoute: typeof ResponsiblePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slate': {
      id: '/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof SlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/picks': {
      id: '/app/picks'
      path: '/picks'
      fullPath: '/app/picks'
      preLoaderRoute: typeof AppPicksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/advanced': {
      id: '/desk/advanced'
      path: '/advanced'
      fullPath: '/desk/advanced'
      preLoaderRoute: typeof DeskAdvancedRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/health': {
      id: '/desk/health'
      path: '/health'
      fullPath: '/desk/health'
      preLoaderRoute: typeof DeskHealthRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/models': {
      id: '/desk/models'
      path: '/models'
      fullPath: '/desk/models'
      preLoaderRoute: typeof DeskModelsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/record': {
      id: '/desk/record'
      path: '/record'
      fullPath: '/desk/record'
      preLoaderRoute: typeof DeskRecordRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/slate': {
      id: '/desk/slate'
      path: '/slate'
      fullPath: '/desk/slate'
      preLoaderRoute: typeof DeskSlateRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppPicksRoute: typeof AppPicksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppPicksRoute: AppPicksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DeskRouteRouteChildren {
  DeskAdvancedRoute: typeof DeskAdvancedRoute
  DeskHealthRoute: typeof DeskHealthRoute
  DeskModelsRoute: typeof DeskModelsRoute
  DeskRecordRoute: typeof DeskRecordRoute
  DeskSlateRoute: typeof DeskSlateRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteRouteChildren: DeskRouteRouteChildren = {
  DeskAdvancedRoute: DeskAdvancedRoute,
  DeskHealthRoute: DeskHealthRoute,
  DeskModelsRoute: DeskModelsRoute,
  DeskRecordRoute: DeskRecordRoute,
  DeskSlateRoute: DeskSlateRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteRouteWithChildren = DeskRouteRoute._addFileChildren(
  DeskRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DeskRouteRoute: DeskRouteRouteWithChildren,
  AdvancedRoute: AdvancedRoute,
  HealthRoute: HealthRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecordRoute: RecordRoute,
  ResponsiblePlayRoute: ResponsiblePlayRoute,
  SlateRoute: SlateRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronTickRoute: ApiCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
