/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SlateRouteImport } from './routes/slate'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SlateRoute = SlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ledger': typeof LedgerRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ledger': typeof LedgerRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ledger': typeof LedgerRoute
  '/record': typeof RecordRoute
  '/slate': typeof SlateRoute
  '/api/cron/tick': typeof ApiCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/advanced' | '/ledger' | '/record' | '/slate' | '/api/cron/tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advanced' | '/ledger' | '/record' | '/slate' | '/api/cron/tick'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/ledger'
    | '/record'
    | '/slate'
    | '/api/cron/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  LedgerRoute: typeof LedgerRoute
  RecordRoute: typeof RecordRoute
  SlateRoute: typeof SlateRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slate': {
      id: '/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof SlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  LedgerRoute: LedgerRoute,
  RecordRoute: RecordRoute,
  SlateRoute: SlateRoute,
  ApiCronTickRoute: ApiCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
